name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build_windows:
    name: Windows Build and Check
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Odin
        shell: cmd
        run: |
          git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
          cd Odin
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./build.bat
          ./odin version
          ./odin report

      - name: Check All
        shell: cmd
        run: |
          set FLAGS=-debug
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          .\Odin\odin build examples/hello
          .\Odin\odin build examples/hello %FLAGS%
          .\Odin\odin build examples/hello %FLAGS% -define:GPU_BACKEND=WGPU
          .\Odin\odin build examples/hello %FLAGS% -define:GPU_BACKEND=Dummy -define:PLATFORM_BACKEND=Dummy

          .\Odin\odin build examples/hello_minimal
          .\Odin\odin build examples/stress_test_3d
          .\Odin\odin build examples/simple_3d
          .\Odin\odin build examples/fps
          .\Odin\odin build examples/planet_snake
