name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build_windows:
    name: Windows Build and Check
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Odin
        shell: cmd
        run: |
          git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
          cd Odin
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./build.bat
          ./odin version
          ./odin report
          echo %CD%>> %GITHUB_PATH%

      - name: Check All
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          odin check examples/hello -vet -strict-style -debug
          odin check examples/hello -vet -strict-style -debug -define:GPU_BACKEND=WGPU
          odin check examples/hello -vet -strict-style -debug -define:GPU_BACKEND=Dummy -define:PLATFORM_BACKEND=Dummy
